application/urls.py
from django.conf.urls import url
from application import views
from django.urls import path, re_path
app_name='application'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    re_path(r'profile/(?P<course>[a-zA-Z]+)$', views.profile, name='profile'),
    re_path(r'profile_t/(?P<course>[a-zA-Z]+)$', views.profile_t, name='profile_t'),
    path(r'logout/', views.logout_user, name='logout'),
    re_path(r'assignment/(?P<assign_id>[0-9]+)$', views.detail, name='detail'),
    re_path(r'assignment_t/(?P<assign_id>[0-9]+)$', views.detail_t, name='detail_t'),
    re_path(r'sol_detail_t/(?P<sol_id>[0-9]+)$', views.sol_detail_t, name='sol_detail_t'),
    re_path(r'sol_submit/(?P<assignment_id>[0-9]+)$', views.submit, name='submit'),
    re_path(r'add_t/(?P<course>[a-zA-Z]+)$', views.add_t, name='add_t'),
    path('t_courses/',views.t_courses,name="t_courses"),
    path('s_courses/',views.s_courses,name="s_courses"),
    path('t_videos/',views.teacherVideos,name="hasti"),
    path('videos/upload/',views.teacherUpload, name = "teacher_video_upload"),
    path('videos/<int:video_id>',views.videoDetail, name="teacher_video_detail"),
    path('s_videos/',views.studentVideos,name="student_videos")]

bp_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import application
from django.urls import path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('application/', include('application.urls', namespace='application')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

application/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
import django
import datetime


class Course(models.Model):
	COURSE_CHOICE=(
		('bp','bp'),
	)
	name=models.CharField(choices=COURSE_CHOICE,max_length=100,default="")
	def __str__(self):
		return self.name

class UserProfile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	COURSE_CHOICE=('bp','bp')

	IDENTITY_CHOICE=(
		('teacher','teacher'),
		('student', 'student'),
		
	)
	identity=models.CharField(choices=IDENTITY_CHOICE,max_length=100,default="student")
	courses=models.CharField(COURSE_CHOICE,max_length=500,default="")
	full_name = models.CharField(max_length = 100)

	roll_no = models.CharField(max_length = 9, unique=True)
	created = models.DateField(editable=False, null=True)
	
	def __str__(self):
		return self.roll_no

	def save(self):
		if not self.id:
			self.roll_no = self.user.username
			self.created = datetime.date.today()
		super(UserProfile, self).save()

class Assignment(models.Model):

	course=models.ForeignKey(Course,on_delete=models.SET_NULL, null=True,default="")
	teacher=models.ForeignKey(UserProfile,on_delete=models.SET_NULL, null=True,default="")
	name = models.CharField(max_length = 200)
	questions = models.TextField(max_length = 1000)
	solutionfiles=models.FileField(upload_to="medias/solutions",default="")
	num=models.IntegerField(default=1)
	created = models.DateField(editable=False, null=True)
	updated = models.DateTimeField(editable=False, null=True)
	deadline = models.DateField()
	def __str__(self):
		return self.name

	def save(self):
		if not self.id:
			self.created = datetime.date.today()
		self.updated = datetime.datetime.today()
		super(Assignment, self).save()

class Solution(models.Model):
	assignment = models.ForeignKey(Assignment, on_delete=models.SET_NULL, null=True)
    
	student = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True)
	submission_date = models.DateField()
	title=models.CharField(max_length=100,default="")
	questionfiles=models.FileField(upload_to="medias/questions",default="")
	body=models.TextField(max_length=1000,default="")
	points=models.FloatField(default=0.)
	comments=models.CharField(max_length=200,default="")
	worked=models.BooleanField(default=False)
	def __str__(self):
		return self.title

	def save(self):
		self.submission_date = datetime.date.today()
		super(Solution, self).save()
class Videos(models.Model):
	caption = models.CharField(max_length=100)
	vids = models.FileField(upload_to="medias/video")
	def __str__(self):
	    return self.caption

application/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Assignment, Solution, UserProfile,Videos
import datetime

class SolutionForm(forms.ModelForm):
	class Meta:
		model = Solution
		fields = ['title','body']

	def __init__(self, *args, **kwargs):
		
		user = kwargs.pop('user')

		course=kwargs.pop('course')

		super(SolutionForm, self).__init__(*args, **kwargs)


class AssignmentForm(forms.ModelForm):
	class Meta:
		model=Assignment
		fields=['num','name','questions','deadline']

class SolCreditForm(forms.ModelForm):
	class Meta:
		model=Solution
		fields=['points','comments']

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ['full_name']
class CreateVideo(forms.ModelForm):
	class Meta :
		model = Videos
		fields = ['caption', 'vids']

application/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404 ,redirect,reverse
from .forms import SolutionForm, UserProfileForm,AssignmentForm,SolCreditForm,CreateVideo
from .models import Assignment, Solution, UserProfile,Course,Videos
import datetime

def index(request):
	if  request.user.is_authenticated:
		return redirect('application:profile')
		
	else:
		return render(request, 'application/index.html')

def detail(request, assign_id):

		user = request.user
		assign = get_object_or_404(Assignment, pk=assign_id)
		return render(request, 'application/details.html', {'assignment': assign, 'user': user,'course':assign.course.name})

def detail_t(request, assign_id):

		user = request.user
		assign = get_object_or_404(Assignment, pk=assign_id)
		sol_set=Solution.objects.filter(assignment__id=assign_id)

		return render(request, 'application/details_t.html', {'assignment': assign,'sol_set':sol_set, 'user': user,'course':assign.course.name})
def sol_detail_t(request,sol_id):

		sol=get_object_or_404(Solution,pk=sol_id)
		if request.method=='POST':
			sol.comments=request.POST['comments']
			sol.points=request.POST['points']
			sol.save()
			return redirect('application:profile_t', course=sol.assignment.course)

		return render(request,'application/sol_details_t.html',{'sol':sol})
def profile(request,course):


		usr_profile = UserProfile.objects.get(user=request.user)
		usr_assign = Assignment.objects.filter(course__name=course)
		now=datetime.date.today()
		dead = []
		idx=[]
		asset = []
		cut = 1
		while True:
			usr_assign = Assignment.objects.filter(course__name=course,
												   num=cut)
			if len(usr_assign) == 0:
				break
			else:
				idx.append(cut)
				if usr_assign[0].deadline<now:
					dead.append(0)
				else:
					dead.append(1)

				asset.append(usr_assign)
				cut = cut + 1
		usr_soln = Solution.objects.filter(student=usr_profile)
		asset.reverse()
		dead.reverse()
		idx.reverse()

		return render(request, 'application/profile.html', {
			'asset': zip(asset,dead,idx),
			'solutions': usr_soln,
			'course':course,
		})

def profile_t(request,course):


		usr_profile = UserProfile.objects.get(user=request.user)
		now=datetime.date.today()
		idx=[]
		dead=[]
		asset=[]
		cut=1
		while True:

			usr_assign = Assignment.objects.filter(course__name=course, teacher=usr_profile, num=cut)
			if len(usr_assign)==0:
				break
			else:
				idx.append(cut)
				if usr_assign[0].deadline<now:
					dead.append(0)
				else:
					dead.append(1)
				asset.append(usr_assign)
				cut=cut+1
		asset.reverse()
		dead.reverse()
		idx.reverse()
		return render(request, 'application/profile_t.html', {
			'asset': zip(asset,dead,idx),
			'course':course,
		})



def logout_user(request):
	logout(request)
	return HttpResponseRedirect('/application/')

def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		identity=request.POST['identity']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				
				user_profile=UserProfile.objects.get(user=user,identity=identity)
				if user_profile is not None:
					if identity=='student':
						return redirect('application:s_courses')
					else:
						return redirect('application:t_courses')

			else:
				return render(request, 'application/index.html', {'error_message': 'Your account has been disabled'})
		else:
			return render(request, 'application/index.html', {'error_message': 'Invalid login'})
	return render(request, 'application/index.html')

def s_courses(request):
	user_profile=UserProfile.objects.get(user=request.user)
	if user_profile is None:
		return render(request, 'application/index.html')
	else:
		courses=user_profile.courses
		course_list=courses.split('-')
		if course_list is not None:
			return render(request,'application/courses.html',{'course_list':course_list})


def t_courses(request):
	user_profile=UserProfile.objects.get(user=request.user)
	if user_profile is None:
		return render(request, 'application/index.html')
	else:
		courses=user_profile.courses
		course_list=courses.split('-')
		if course_list is not None:
			return render(request,'application/courses_t.html',{'course_list':course_list})

def submit(request,assignment_id):

		assignment=Assignment.objects.get(id=assignment_id)
		if request.method == 'POST':

			print(request.POST['title'])
			form = SolutionForm(user=request.user,course=assignment.course, data=request.POST)
			if form.is_valid():
				solution = form.save(commit=False)
				solution.student = UserProfile.objects.get(user=request.user)
				solution.assignment=assignment

				pre_sol=Solution.objects.filter(assignment__id=assignment_id,student=solution.student).all()
				pre_sol.delete()
				solution.save()
                

				return redirect('application:profile',course=assignment.course)

		else:
		
		    

			form = SolutionForm(user=request.user,course=assignment.course)
		return render(request, 'application/sol_submit.html', {'form': form,'course':assignment.course})

def add_t(request,course):

		if request.method == 'POST':
			form = AssignmentForm(data=request.POST)
			if form.is_valid():
				ass = form.save(commit=False)
				course=Course.objects.get(name=course)
				ass.teacher = UserProfile.objects.get(user=request.user)
				ass.course=course
				ass.save()

				return redirect('application:profile_t',course=course)

		else:
		
			

			form = AssignmentForm()
		return render(request, 'application/add_t.html', {'form': form,'course':course})
def teacherVideos(request):
	videos = Videos.objects.all()
	context={'videos':videos}
	return render(request,"application/teacher_videos.html",context)
def studentVideos(request):
	videos = Videos.objects.all()
	context={'videos':videos}
	return render(request,"application/student_videos.html",context)
def teacherUpload(request):
	
	if request.method=="POST":
		form = CreateVideo(request.POST , request.FILES)
		if form.is_valid():
			form.save()
			return  HttpResponseRedirect('/application/t_courses/')
	else:
	 form = CreateVideo()	
	 context={'form':form}
	 return render(request,"application/teacher_video_upload.html",context)

def videoDetail(request , video_id):
    vid = Videos.objects.get(id=video_id)
    context = {"video": vid}
    return render(request,"application/teacher_video_detail.html",context)

templates/application/base.html
<!DOCTYPE html>

<body>
{% block body %}
{% endblock %}
</body>
</html>

templates/application/base_profile_t.html
<!DOCTYPE html>
<html lang="en">
<body>
              <div>
              <a href="{% url 'application:profile_t' course=course %}">Assignments</a></div>
              <div><a href="{% url 'application:add_t' course=course %}">Add</a></div>
              <div><a href="{% url 'application:logout' %}">
                         Logout
                  </a>
              </div>
{% block body %}
{% endblock %}
</body>
</html>

templates/application/courses.html
{% extends 'application/base.html' %}

{% block body %}
<a href="{% url 'application:logout' %}">
 Logout
</a>

<div class="container">
{% for course in course_list %}
    <a href="{% url 'application:profile' course=course %}">{{ course }}</a>
{% endfor %}

</div>

<div>
 
 <a href="{% url 'application:student_videos' %}">movies</a>

	
</div>
{% endblock %}

templates/application/courses_t.html
{% extends 'application/base.html' %}

{% block body %}
<a href="{% url 'application:logout' %}">
 logout
</a>

<div class="container">
{% for course in course_list %}
    <a href="{% url 'application:profile_t' course=course %}">{{ course }}</a>
   
{% endfor %}

</div>
<div>
 
 <a href="{% url 'application:hasti' %}">movies</a>

	
</div>
{% endblock %}

templates/application/details.html
{% extends 'application/base_profile.html' %}
{% block title %}{{ assignment }}{% endblock %}

{% block body %}
<div>
    <div class="row">
        <h3>{{ assignment.name }}</h1>
        <h5>Deadline: {{ assignment.deadline }}</h3>
        <hr>
        <h4>Questions:</h4>
        <p>{{ assignment.questions }}</p>
        <hr>
        <button><a href="{% url 'application:submit' assignment.id %}">Add Your Submit</a></button>
    </div>
</div>
{% endblock %}

templates/application/details_t.html
{% extends 'application/base_profile_t.html' %}
{% block title %}{{ assignment }}{% endblock %}

{% block body %}

        <h3>{{ assignment.name }}</h1>
        <h5>Deadline: {{ assignment.deadline }}</h3>
        <hr>
        <h4>Questions:</h4>
        <p>{{ assignment.questions }}</p>
        <hr>

    <div >

     <table>
          <thead>
            <tr>
              <th>Title</th>
                <th>SubDate</th>
              <th>Author</th>
            </tr>
          </thead>
          <tbody>
          {% if sol_set %}
            {% for sol in sol_set %}
                  <tr>
                    <td><a href="{% url 'application:sol_detail_t' sol_id=sol.id %}">solution</a></td>
                    <td>{{ sol.submission_date }}</td>

                    <td>{{ sol.student.roll_no }}</td>
                  </tr>
            {% endfor %}
          </tbody>
        </table>
        {% endif %}

    </div>
{% endblock %}

templates/application/index.html
{% extends 'application/base.html' %}
{% block title %}Home{% endblock %}
{% block index_active %}active{% endblock %}

{% block body %}
                
<h3>Log In</h3>
{% if error_message %}
<div class="alert alert-danger">
<strong>{{ error_message }}</strong>
</div>
 {% endif %}
<form role="form" action="{% url 'application:login'%}" method="post" enctype="multipart/form-data">
   {% csrf_token %}
    <div >
         Username:
         <div>
             <input id="id_username" maxlength="30" name="username" type="text">
         </div>
    </div>

        <div >
              Password:
             <div>
               <input id="id_password" maxlength="30" name="password" type="password">
             </div>
        </div>

            <div >
                 Identity:
              <div >
                 <input id="id_identity" type="radio" name="identity" value="teacher"/>Teacher
                 <input id="id_identity" type="radio" name="identity" value="student" checked="checked"/>Student
               </div>
                </div>

        <div >
             <div>
              <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
</form>
                
 

{% endblock %}

templates/application/profile.html
{% extends 'application/base_profile.html' %}

{% block body %}


    {% if error_message %}
      <div class="alert alert-danger">
        <strong>{{ error_message }}</strong>
      </div>
    {% endif %}
        <h3>{{ user.username }}'s Assignments</h3>

          {% if asset %}
              {% for assignments,dead,idx in asset %}
                   
              <div>
              <button id="{{ forloop.counter }}">{{ idx }} exercise</button>
              <table  id="{{ forloop.counter }}">
          <thead>
            <tr>
              <th>Assignment</th>
              <th>Deadline</th>
              <th>Solution</th>
              <th>Points</th>
              <th>Comments</th>
            </tr>
          </thead>
          <tbody>
            {% for assign in assignments %}
                  <tr id="aaa">
                  {% ifequal dead 1 %}
                    <td><a href="{% url 'application:detail' assign.id %}">{{ assign.name }}</a></td>
                      <td >{{ assign.deadline }}</td>
                      {% else %}
            <td><a href="{% url 'application:detail' assign.id %}">{{ assign.name }}</a></td>
                      <td >{{ assign.deadline }}</td>
                  {% endifequal %}

                    {% for sol in solutions %}
                      {% if assign.id == sol.assignment.id %}
                        <td>{{ sol.title }}</td>
                          {% ifnotequal sol.points 0.0 %}

                          <td>{{ sol.points }}</td>
                          {% endifnotequal %}
                            <td>{{ sol.comments }}</td>
                      {% endif %}
                    {% endfor %}
                  </tr>
            {% endfor %}

          </tbody>
        </table>
              </div>
              {% endfor %}
        {% endif %}

{% endblock %}

templates/application/profile_t.html
{% extends 'application/base_profile_t.html' %}

{% block body %}

    {% if error_message %}
      <div class="alert alert-danger">
        <strong>{{ error_message }}</strong>
      </div>
    {% endif %}
        <h3>{{ user.username }}'s Assignments</h3>
        {% if asset %}

              {% for assignments,dead,idx in asset %}
                  
<div>
<button  id="{{ forloop.counter }}">{{ idx }}exercise</button>
    <table  id="{{ forloop.counter }}">

          <tbody>
            {% for assign in assignments %}
                    <tr id="aaa">
                    <td><a href="{% url 'application:detail_t' assign.id %}">{{ assign.name }}</a></td>
                    </tr>

            {% endfor %}
          </tbody>
        </table>
</div>
            {% endfor %}
        {% endif %}

{% endblock %}

templates/application/sol_submit.html
{% extends 'application/base_profile.html' %}
{% block body %}


<h3>Submit a Solution</h3>
{% if error_message %}
    <div class="alert alert-danger">
    <strong>{{ error_message }}</strong>
    </div>
{% endif %}
<form role="form" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    Title:
<input name="title" maxlength="200" type="text" onpaste="return false" oncontextmenu="return false" oncopy="return false" oncut="return false"/>
                
<br>
<br>
Description:
<br>
<textarea name="body" rows="10" cols="50" type="text" onpaste="return false" oncontextmenu="return false" oncopy="return false" oncut="return false">
</textarea>
<br>

<button type="submit" class="btn btn-success">Submit</button>
</form>

{% endblock %}

templates/application/student_videos.html
{% extends 'application/base.html' %}
{% block body %}
<a href="{% url 'application:logout' %}">
 Logout
</a>

{% for video in videos %}

<div>
  <a href="{% url 'application:teacher_video_detail' video.id %}">{{ video.caption }}</a>
</div>

{% endfor %}
{% endblock %}

templates/application/teacher_video_detail.html
{% extends 'application/base.html' %}
{% block body %}
<video controls="controls">
	<source src="{{ video.vids.url }}" type="video/mp4">
</video>
{% endblock %}

templates/application/teacher_video_upload.html
{% extends 'application/base.html' %}
{% block body %}
<form action="" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="submit">
</form>
{% endblock %}

templates/application/teacher_videos.html
{% extends 'application/base.html' %}
{% block body %}
<a href="{% url 'application:logout' %}">
 Logout
</a>

{% for video in videos %}

<div>
  <a href="{% url 'application:teacher_video_detail' video.id %}">{{ video.caption }}</a>
</div>

{% endfor %}
<br>
<hr>
<h3>
<div>
<a  href= "{% url 'application:teacher_video_upload' %}" style="background-color: red">upload</a>
</div>
</h3>
{% endblock %}